### ISSUE TITLE
How to import

### ISSUE THREAD

**Issue by tejaslodaya** [RonanCN/GuideBackgroundColorAnimation#2]
How do i import this library in android studio? 
I mean compile 'cn.taurusxi.guidebackgroundcoloranimation.1.0' or what? PLease guide

**Comment by gxshao** [comment]
GuideBackgroundColorAnimation/library/src/main/java/cn/taurusxi/guidebackgroundcoloranimation/library/
you gonna find .java file in this path..and copy it into your project and create new view in your layout file...and follow the sample code
